# Generated by Django 6.0.3 on 2026-03-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
